package az.tribe.lifeplanner.ui.navigation

sealed class Screen(val route: String) {
    object Onboarding : Screen("onboarding")
    object Home : Screen("home")
    object Goals : Screen("goals")
    object Profile : Screen("profile")
    object AddGoal : Screen("add_goal")
    object Analytics : Screen("analytics")
    object Marketplace : Screen("marketplace")
    object QuestMarketplace : Screen("marketplace_quest")
    object EditGoal : Screen("edit_goal/{goalId}")
    object GoalDetail : Screen("goal_detail/{goalId}")
    object MilestoneDetail : Screen("milestone_detail/{goalId}/{milestoneId}")
    object AiGoalGeneration : Screen("ai_goal_generation")
    object HabitTracker : Screen("habit_tracker")
    object Journal : Screen("journal")
    object JournalWizard : Screen("journal_wizard?goalId={goalId}")
    object JournalEntryDetail : Screen("journal_entry_detail/{entryId}")
    object Achievements : Screen("achievements")
    object DependencyGraph : Screen("dependency_graph")
    object DependencyGraphForGoal : Screen("dependency_graph/{goalId}")
    object AIChat : Screen("ai_chat")
    object AIChatSession : Screen("ai_chat/{sessionId}")
    object CreateCoach : Screen("create_coach")
    object EditCoach : Screen("edit_coach/{coachId}")
    object CreateGroup : Screen("create_group")
    object EditGroup : Screen("edit_group/{groupId}")
    object Reviews : Screen("reviews")
    object Templates : Screen("templates")
    object AddGoalFromTemplate : Screen("add_goal_from_template/{templateId}")
    object Reminders : Screen("reminders")
    object LifeBalance : Screen("life_balance")
    object BackupSettings : Screen("backup_settings")
}